title: Leopride
description: 14+ Glorious Years of Excellence


permalink: /blog/:title/

sass:
  sass_dir: /assets/css/_sass
  style: compressed


include:
  - _pages
exclude:
  - .cpanel.yml

destination: public

plugins:
  - jekyll-seo-tag
